sys_path: 
  - ../attack_detector
  - ../detect_attacks
  - ../lib
  - ../context_profile
SCEME:
  path: ../detect_attacks
  prefix: voc_checkpoints_
  gamma: 9.0
  checkpoint:
    name: model
    # epoch: !!str 2
    epoch: !!str 4
    version: !!str 0.0
SIN:
  path: ../output/faster_rcnn_end2end
  ckpt: ../output/faster_rcnn_end2end/voc_2007_trainval+voc_2012_trainval/VGGnet_wt_context/VGGnet_wt_context.ckpt
  surrogate_ckpt: null
  # surrogate_ckpt: /data/ml-hdd/voc_2012_trainval/VGGnet_my_0.200/VGGnet_iter_350000.ckpt
  perturbation_path: /data/ml-hdd/perturbations/IFGSM_appear_nomask_sin
  # perturbation_path: /data/ml-hdd/perturbations/IFGSM_hiding_nomask_sin
  # perturbation_path: /data/ml-hdd/perturbations/IFGSM_miscls_nomask_constrain_all

classes:
  # ['__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'diningtable', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
  ['__background__', 'aeroplane', 'bicycle', 'bird', 'boat',
  'bottle', 'bus', 'car', 'cat', 'chair',
  'cow', 'diningtable', 'dog', 'horse',
  'motorbike', 'person', 'pottedplant',
  'sheep', 'sofa', 'train', 'tvmonitor']

# classes:

target_classes:
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  # [0,1,3,12,16,20,21,23,24,46,57,61]


fast_rcnn:
  config_path: ../experiments/cfgs/faster_rcnn_end2end.yml

data:
  set_name: voc_2007_test
  # list_path: ../data/coco/annotations/coco_2014_valminusminival.txt
  list_path: ../data/VOCdevkit/VOC2007/ImageSets/Main/test.txt

ptrs_output_dir_fmt: /dev/null